### ISSUE TITLE
Cannot build with `double-conversion-2.0.3.0`

### ISSUE THREAD

**Issue by ocharles** [AJChapman/formatting#77]
```
Building library for formatting-7.1.3..
[ 1 of 13] Compiling Data.Text.Format.Functions ( src/Data/Text/Format/Functions.hs, dist/build/Data/Text/Format/Functions.o, dist/build/Data/Text/Format/Functions.dyn_o )
[ 2 of 13] Compiling Data.Text.Format.Types ( src/Data/Text/Format/Types.hs, dist/build/Data/Text/Format/Types.o, dist/build/Data/Text/Format/Types.dyn_o )
[ 3 of 13] Compiling Formatting.Buildable ( src/Formatting/Buildable.hs, dist/build/Formatting/Buildable.o, dist/build/Formatting/Buildable.dyn_o )
[ 4 of 13] Compiling Data.Text.Format ( src/Data/Text/Format.hs, dist/build/Data/Text/Format.o, dist/build/Data/Text/Format.dyn_o )

src/Data/Text/Format.hs:30:1: error:
    Could not load module ‘Data.Double.Conversion.Text’
    it is a hidden module in the package ‘double-conversion-2.0.3.0’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import           Data.Double.Conversion.Text (toFixed, toShortest)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think `double-conversion-2.0.3` should really have been `double-conversion-2.1` as there's a breaking API change. I think the fix is to import `Data.Double.Conversion.Convertable` now.

**Comment by ocharles** [comment]
I see 2.0.4.1 just came out that restores the API, so I think this is fixed now.
